backend:
  name: github
  repo: LimaBruno/personal-blog
  branch: master
  site_domain: brunocesarlima.com.br

media_folder: "static/assets/img"
public_folder: "/assets/img"
publish_mode: editorial_workflow
slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'post'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
      - {label: "Image", name: "thumbnail", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["dev","infra", "agil", "ux/ui", "gest", "seg","misc","cms"]}
      - {
          label: "Color",
          name: "background",
          widget: "select",
          options: [
            { label: "Dev", value: "#EA2027" },
            { label: "Infra", value: "#00801C" },
            { label: "Agil", value: "#2C3E50" },
            { label: "UX/UI", value: "#7412FF" },
            { label: "Gest", value: "#006266" },
            { label: "Seg", value: "#0652DD" },
            { label: "Misc", value: "#73626E" },
            { label: "CMS", value: "#6D214F" },
          ]
        }
      - {label: "Body", name: "body", widget: "markdown"}